import "./globals.css";
import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import Script from "next/script";

const merriweather = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Hoai Tran Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Hoai Tran Dev</title>
        <meta
          name="description"
          content="I’m a full-stack developer. I am not satisfied with my skill and working hard towards a higher skill. I have been developing web applications for over 4 years. I aim to make high-quality works with 100% effort for all customers."
        />
        <link
          rel="shortcut icon"
          href="/images/avt.jpg"
          className="rounded-full"
        ></link>
        <meta property="og:image" content="/images/avt.jpg" />
        <meta property="og:title" content="Hoai Tran Dev" />
        <meta
          property="og:description"
          content="I’m a full-stack developer. I am not satisfied with my skill and working hard towards a higher skill. I have been developing web applications for over 4 years. I aim to make high-quality works with 100% effort for all customers"
        />
        <meta property="og:url" content="https://hoaitran.netlify.app" />
        <meta property="og:type" content="website" />

        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/images/avt.jpg"
          className="rounded-full"
        />
        {/* Add the Google Tag Manager script */}
        <Script id="gtm-script" strategy="afterInteractive">
          {`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-PGRSWW4X');`}
        </Script>
      </head>
      <body className={`${merriweather.className} overflow-x-hidden relative`}>
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-PGRSWW4X"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>
        <video
          autoPlay
          loop
          muted
          className="absolute inset-0 w-full h-full object-cover"
        >
          <source src="/videos/header-bg-vi.mp4" type="video/mp4" />
        </video>
        <div className="relative bg-[rgba(0,0,0,0.5)]">{children}</div>
      </body>
    </html>
  );
}
